#!/bin/bash
set -e

echo "Connecting Superset to PostGIS and registering datasets..."
docker exec -i superset superset shell < scripts/superset_init_geodata.py

echo "=========================================================="
echo "Superset Configuration Complete!"
echo "=========================================================="
echo "To access the Superset UI:"
echo "1. Open http://localhost:8088 in your browser."
echo "2. Log in with credentials: Username: admin, Password: admin"
echo "3. Go to Settings -> Database Connections to verify 'Geodata_PostGIS' is connected."
echo "4. Go to Data -> Datasets to verify 'buildings', 'roads', and 'rainfall' are registered."
echo ""
echo "To create the Deck.gl Polygon chart for Buildings:"
echo "- Click '+' in the top right -> Chart."
echo "- Select the 'buildings' dataset."
echo "- Choose 'deck.gl Polygon' as the visualization type."
echo "- In the Query section:"
echo "  * Set the Polygon Column to 'geometry'."
echo "  * Set the Stroke/Fill Color as desired (e.g., Red/Orange for flood risk areas)."
echo "  * Configure hover tooltip fields (e.g. name, building type)."
echo ""
echo "To create the Deck.gl Scatterplot chart for Rainfall:"
echo "- Click '+' in the top right -> Chart."
echo "- Select the 'rainfall' dataset."
echo "- Choose 'deck.gl Scatterplot' as the visualization type."
echo "- In the Query section:"
echo "  * Set Longitude & Latitude columns."
echo "  * Set Point Radius based on 'precipitation_sum' to map rainfall intensity."
echo ""
echo "Combine both charts into a new Dashboard named 'Urban Flood Risk Dashboard'."
echo "=========================================================="
